apiVersion: v1
kind: Namespace
metadata:
  name: models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
